-- 1. Create Tables
CREATE TABLE users (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  reg_number TEXT NOT NULL,
  branch TEXT,
  year INTEGER,
  avatar_url TEXT,
  role TEXT DEFAULT 'student' CHECK (role IN ('student', 'organiser', 'admin')),
  campus TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE TABLE clubs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  logo_url TEXT,
  banner_url TEXT,
  description TEXT,
  category TEXT,
  campus TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE TABLE club_organisers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id BIGINT REFERENCES clubs ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES users ON DELETE CASCADE NOT NULL,
  approved BOOLEAN DEFAULT FALSE,
  approved_at TIMESTAMP WITH TIME ZONE,
  UNIQUE(club_id, user_id)
);

CREATE TABLE events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id BIGINT REFERENCES clubs ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  banner_url TEXT,
  venue TEXT,
  event_date TIMESTAMP WITH TIME ZONE NOT NULL,
  registration_deadline TIMESTAMP WITH TIME ZONE,
  max_capacity INTEGER,
  event_type TEXT CHECK (event_type IN ('formal', 'announcement')),
  campus TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE TABLE registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT REFERENCES events ON DELETE CASCADE NOT NULL,
  student_id UUID REFERENCES users ON DELETE CASCADE NOT NULL,
  registered_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  status TEXT DEFAULT 'confirmed',
  UNIQUE(event_id, student_id)
);

CREATE TABLE follows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID REFERENCES users ON DELETE CASCADE NOT NULL,
  club_id BIGINT REFERENCES clubs ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  UNIQUE(student_id, club_id)
);

CREATE TABLE going_out_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  posted_by UUID REFERENCES users ON DELETE CASCADE NOT NULL,
  event_name TEXT NOT NULL,
  event_location TEXT NOT NULL,
  event_date TIMESTAMP WITH TIME ZONE NOT NULL,
  source_url TEXT,
  looking_for TEXT CHECK (looking_for IN ('buddies', 'teammates', 'both')),
  spots_needed INTEGER,
  details TEXT,
  expires_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE TABLE going_out_interests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES going_out_posts ON DELETE CASCADE NOT NULL,
  student_id UUID REFERENCES users ON DELETE CASCADE NOT NULL,
  message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  UNIQUE(post_id, student_id)
);

CREATE TABLE team_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  posted_by UUID REFERENCES users ON DELETE CASCADE NOT NULL,
  hackathon_name TEXT NOT NULL,
  event_date TIMESTAMP WITH TIME ZONE NOT NULL,
  skills_needed TEXT[],
  spots_available INTEGER,
  description TEXT,
  status TEXT DEFAULT 'open' CHECK (status IN ('open', 'closed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE TABLE team_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_post_id BIGINT REFERENCES team_posts ON DELETE CASCADE NOT NULL,
  student_id UUID REFERENCES users ON DELETE CASCADE NOT NULL,
  message TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  UNIQUE(team_post_id, student_id)
);

CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  posted_by UUID REFERENCES users ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  tech_stack TEXT[],
  looking_for TEXT CHECK (looking_for IN ('co-builder', 'mentor', 'feedback')),
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'completed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE TABLE announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id BIGINT REFERENCES clubs ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  pinned_until TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users ON DELETE CASCADE NOT NULL,
  type TEXT NOT NULL,
  message TEXT NOT NULL,
  read BOOLEAN DEFAULT FALSE,
  reference_id BIGINT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE TABLE project_interests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects ON DELETE CASCADE NOT NULL,
  student_id UUID REFERENCES users ON DELETE CASCADE NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  UNIQUE(project_id, student_id)
);


-- 2. Enable Row Level Security
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE clubs ENABLE ROW LEVEL SECURITY;
ALTER TABLE club_organisers ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE going_out_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE going_out_interests ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;


-- 3. RLS Policies

-- Users: Read all users. Update own profile.
CREATE POLICY "Anyone can read users" ON users FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON users FOR UPDATE USING (auth.uid() = id);

-- Clubs: Anyone can read
CREATE POLICY "Anyone can read clubs" ON clubs FOR SELECT USING (true);
CREATE POLICY "Admin can manage clubs" ON clubs FOR ALL USING (
  EXISTS (SELECT 1 FROM users WHERE users.id = auth.uid() AND role = 'admin')
);

-- Club Organisers: Read all. Admin updates.
CREATE POLICY "Anyone can read club_organisers" ON club_organisers FOR SELECT USING (true);
CREATE POLICY "Admin can approve club_organisers" ON club_organisers FOR UPDATE USING (
  EXISTS (SELECT 1 FROM users WHERE users.id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Admin can manage club_organisers" ON club_organisers FOR ALL USING (
  EXISTS (SELECT 1 FROM users WHERE users.id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Users can request to be organiser" ON club_organisers FOR INSERT WITH CHECK (
  auth.uid() = user_id
);

-- Events: Read all. Organisers insert/update.
CREATE POLICY "Anyone can read events" ON events FOR SELECT USING (true);
CREATE POLICY "Approved organisers can insert events" ON events FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM club_organisers WHERE club_id = events.club_id AND user_id = auth.uid() AND approved = true)
);
CREATE POLICY "Approved organisers can update events" ON events FOR UPDATE USING (
  EXISTS (SELECT 1 FROM club_organisers WHERE club_id = events.club_id AND user_id = auth.uid() AND approved = true)
);

-- Registrations: Read own or if organiser. Insert/update own.
CREATE POLICY "Users can read own registrations" ON registrations FOR SELECT USING (auth.uid() = student_id);
CREATE POLICY "Organisers can read event registrations" ON registrations FOR SELECT USING (
  EXISTS (SELECT 1 FROM events e JOIN club_organisers co ON e.club_id = co.club_id WHERE e.id = registrations.event_id AND co.user_id = auth.uid() AND co.approved = true)
);
CREATE POLICY "Users can register themselves" ON registrations FOR INSERT WITH CHECK (auth.uid() = student_id);
CREATE POLICY "Users can manage own registration" ON registrations FOR UPDATE USING (auth.uid() = student_id);

-- Follows: Read all. Insert/Update own.
CREATE POLICY "Anyone can read follows" ON follows FOR SELECT USING (true);
CREATE POLICY "Users can follow" ON follows FOR INSERT WITH CHECK (auth.uid() = student_id);
CREATE POLICY "Users can unfollow" ON follows FOR DELETE USING (auth.uid() = student_id);

-- Going Out Posts: Read all. Insert own.
CREATE POLICY "Anyone can read going_out_posts" ON going_out_posts FOR SELECT USING (true);
CREATE POLICY "Users can post" ON going_out_posts FOR INSERT WITH CHECK (auth.uid() = posted_by);
CREATE POLICY "Users can manage own posts" ON going_out_posts FOR ALL USING (auth.uid() = posted_by);

-- Going Out Interests: Read all. Insert own.
CREATE POLICY "Anyone can read going_out_interests" ON going_out_interests FOR SELECT USING (true);
CREATE POLICY "Users can add interest" ON going_out_interests FOR INSERT WITH CHECK (auth.uid() = student_id);
CREATE POLICY "Users can remove interest" ON going_out_interests FOR DELETE USING (auth.uid() = student_id);

-- Team Posts: Read all. Insert/Manage own.
CREATE POLICY "Anyone can read team_posts" ON team_posts FOR SELECT USING (true);
CREATE POLICY "Users can create team posts" ON team_posts FOR INSERT WITH CHECK (auth.uid() = posted_by);
CREATE POLICY "Users can manage own team posts" ON team_posts FOR ALL USING (auth.uid() = posted_by);

-- Team Applications: Read own or if post owner. Insert own.
CREATE POLICY "Users can read own applications" ON team_applications FOR SELECT USING (auth.uid() = student_id);
CREATE POLICY "Post owners can read applications" ON team_applications FOR SELECT USING (
  EXISTS (SELECT 1 FROM team_posts tp WHERE tp.id = team_applications.team_post_id AND tp.posted_by = auth.uid())
);
CREATE POLICY "Users can apply" ON team_applications FOR INSERT WITH CHECK (auth.uid() = student_id);
CREATE POLICY "Users can manage own application" ON team_applications FOR UPDATE USING (auth.uid() = student_id);
CREATE POLICY "Users can delete own application" ON team_applications FOR DELETE USING (auth.uid() = student_id);

-- Projects: Read all. Insert/Manage own.
CREATE POLICY "Anyone can read projects" ON projects FOR SELECT USING (true);
CREATE POLICY "Users can create projects" ON projects FOR INSERT WITH CHECK (auth.uid() = posted_by);
CREATE POLICY "Users can manage own projects" ON projects FOR ALL USING (auth.uid() = posted_by);

-- Announcements: Read all. Organiser Insert/Update.
CREATE POLICY "Anyone can read announcements" ON announcements FOR SELECT USING (true);
CREATE POLICY "Approved organisers can manage announcements" ON announcements FOR ALL USING (
  EXISTS (SELECT 1 FROM club_organisers WHERE club_id = announcements.club_id AND user_id = auth.uid() AND approved = true)
);

-- Notifications: Read/Update own.
CREATE POLICY "Users can read own notifications" ON notifications FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own notifications" ON notifications FOR UPDATE USING (auth.uid() = user_id);


-- 4. Auth Hook & Trigger for Users signup
-- Supabase enforces email restrictions usually in the Dashboard (Authentication -> Providers -> Email Domains).
-- If you want a database trigger to insert a role:

CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  -- Prevent non SRM emails (redundant safety)
  IF NEW.email NOT LIKE '%@srmist.edu.in' THEN
    RAISE EXCEPTION 'Only @srmist.edu.in emails are allowed';
  END IF;

  INSERT INTO public.users (id, email, full_name, reg_number, branch, year, role)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'reg_number',
    NEW.raw_user_meta_data->>'branch',
    (NEW.raw_user_meta_data->>'year')::integer,
    'student'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 5. Storage Buckets & Policies
INSERT INTO storage.buckets (id, name, public) VALUES ('avatars', 'avatars', true);
INSERT INTO storage.buckets (id, name, public) VALUES ('club-assets', 'club-assets', true);
INSERT INTO storage.buckets (id, name, public) VALUES ('event-banners', 'event-banners', true);

CREATE POLICY "Avatar images are publicly accessible" ON storage.objects FOR SELECT USING (bucket_id = 'avatars');
CREATE POLICY "Anyone can upload an avatar" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'avatars' AND auth.role() = 'authenticated');
CREATE POLICY "Anyone can update own avatar" ON storage.objects FOR UPDATE USING (auth.uid() = owner) WITH CHECK (bucket_id = 'avatars');

CREATE POLICY "Club assets are publicly accessible" ON storage.objects FOR SELECT USING (bucket_id = 'club-assets');
CREATE POLICY "Organisers can upload club assets" ON storage.objects FOR INSERT WITH CHECK (
  bucket_id = 'club-assets' AND 
  EXISTS (SELECT 1 FROM club_organisers WHERE user_id = auth.uid() AND approved = true)
);

CREATE POLICY "Event banners are publicly accessible" ON storage.objects FOR SELECT USING (bucket_id = 'event-banners');
CREATE POLICY "Organisers can upload event banners" ON storage.objects FOR INSERT WITH CHECK (
  bucket_id = 'event-banners' AND 
  EXISTS (SELECT 1 FROM club_organisers WHERE user_id = auth.uid() AND approved = true)
);
